version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: frontend_client
    restart: always
    ports:
      - "3000:3000"  # Puerto de Vite expuesto
    volumes:
      - ./frontend:/app      # Sincronizaci√≥n de c√≥digo en vivo (Hot Reload)
      - /app/node_modules    # Evita que se sobrescriban los m√≥dulos del contenedor
    depends_on:
      - random-movies-service # Espera (l√≥gicamente) a que el backend est√© listo
  
  mongodb:
    image: mongo:latest
    container_name: mongodb_movies
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  mongo-seed:
    image: mongo:latest
    container_name: mongo_seed
    volumes:
      - ./movies-api/data:/data
    command: >
      bash -c "
        echo '‚è≥ Esperando a MongoDB...' &&
        sleep 5 &&
        echo 'üì• Importando pel√≠culas...' &&
        mongoimport --host mongodb --db movies_db --collection movies --type json --file /data/movies.json --drop &&
        echo 'üì• Importando comentarios...' &&
        mongoimport --host mongodb --db movies_db --collection comments --type json --file /data/comments.json --drop &&
        echo '‚úÖ Importaci√≥n completada!'
      "
    depends_on:
      mongodb:
        condition: service_healthy

  movies-api:
    build: ./movies-api
    container_name: movies_api
    restart: always
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/movies_db
    depends_on:
      mongodb:
        condition: service_healthy
      mongo-seed:
        condition: service_completed_successfully
    volumes:
      - ./movies-api:/src
      - /src/node_modules

  random-movies-service:
    build: ./random-movies-service
    container_name: random_movies_service
    restart: always
    ports:
      - "8001:8001"
    depends_on:
      - movies-api
    volumes:
      - ./random-movies-service:/app

volumes:
  mongo_data: