version: "3.8"

services:
  frontend:
    build: ./frontend
    container_name: frontend_client
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - frontend_network
    depends_on:
      - random-movies-service
      - calification-service
      - search-movies-service
      - auth-service
      - ratings-service
      - recommendation-service

  mongodb:
    image: mongo:latest
    container_name: mongodb_movies
    restart: always
    ports:
      - "27017:27017"
    command: [ "mongod", "--quiet" ]
    volumes:
      - mongo_data:/data/db
    networks:
      - backend_network
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  mongo-seed:
    image: mongo:latest
    container_name: mongo_seed
    volumes:
      - ./movies-api/data:/data
    command: >
      bash -c "
        echo '‚è≥ Esperando a MongoDB...' &&
        sleep 5 &&
        echo 'üì• Importando pel√≠culas...' &&
        mongoimport --host mongodb --db movies_db --collection movies --type json --file /data/movies.json --drop &&
        echo 'üì• Importando comentarios...' &&
        mongoimport --host mongodb --db movies_db --collection comments --type json --file /data/comments.json --drop &&
        echo '‚úÖ Importaci√≥n completada!'
      "
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - backend_network

  movies-api:
    build: ./movies-api
    container_name: movies_api
    restart: always
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/movies_db
    depends_on:
      mongodb:
        condition: service_healthy
      mongo-seed:
        condition: service_completed_successfully
    volumes:
      - ./movies-api:/src
      - /src/node_modules
    networks:
      - backend_network

  random-movies-service:
    build: ./random-movies-service
    container_name: random_movies_service
    restart: always
    ports:
      - "8001:8001"
    depends_on:
      - movies-api
    volumes:
      - ./random-movies-service:/app
    networks:
      - frontend_network 
      - backend_network

  search-movies-service:
    build: ./search-movies-service
    container_name: search_movies_service
    restart: always
    ports:
      - "8005:8005"
    depends_on:
      - movies-api
    volumes:
      - ./search-movies-service:/app
    networks:
      - frontend_network 
      - backend_network 

  auth-service:
    build: ./auth-service
    container_name: auth_service
    restart: always
    ports:
      - "8002:8002"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/auth_db
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - ./auth-service:/app
      - /app/node_modules
    networks:
      - frontend_network
      - backend_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_broker
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    networks:
      - backend_network
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  calification-service:
    build: ./calification-service
    container_name: calification_service
    restart: always
    ports:
      - "8003:8003"
    environment:
      - RABBIT_HOST=amqp://admin:admin@rabbitmq:5672
      - QUEUE_NAME=opiniones_queue
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./calification-service:/app
      - /app/node_modules
    networks:
      - frontend_network 
      - backend_network

  opinion-service:
    build: ./opinion-service
    container_name: opinion_service
    restart: always
    environment:
      - RABBIT_HOST=amqp://admin:admin@rabbitmq:5672
      - MONGO_URI=mongodb://mongodb:27017/opiniones_db
      - QUEUE_NAME=opiniones_queue
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    volumes:
      - ./opinion-service:/app
      - /app/node_modules
    networks:
      - backend_network

  ratings-service:
    build: ./ratings-service
    container_name: ratings_service
    restart: always
    ports:
      - "8004:8004"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/opiniones_db
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - ./ratings-service:/app
      - /app/node_modules
    networks:
      - frontend_network
      - backend_network 

  recommendation-service:
    build: ./recommendation-service
    container_name: recommendation_service
    restart: always
    ports:
      - "8006:8006"
    environment:
      - MONGO_URI=mongodb://mongodb:27017
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - ./recommendation-service:/app
    networks:
      - frontend_network  
      - backend_network   

networks:
  frontend_network:
    driver: bridge
    name: dcicflix_frontend
  backend_network:
    driver: bridge
    name: dcicflix_backend

volumes:
  mongo_data: